#data_storage.py

#from base python
import array as arr
from sys import exit as sys_exit

#from other package(s)
import numpy as np

#Adcaelos Imports
from adcaelos.components.base_component import Base_Component
from adcaelos.components.component_enums import Component_Enums
from adcaelos.utilities.sim_utils import Sim_Utils

class Data_Storage(Base_Component):

    def __init__(self, variable_names: str | list[str], initial_values: np.array, next_time: float = 0, num_stored_steps: int = 100, Component_Type=Component_Enums.STORAGE_COMPONENT, name: str = "Storage_Component", UUID: int = None) -> None:
        # Passing Up Default Arguments to Base Component Constructor
        Base_Component.__init__(self, component_type=Component_Type, name=name, UUID=UUID)
        
        # Initialize the data storage dictionary and state name mappings
        
        self.__data_storage = {} # Dictionary to store data generated by this component, with keys as data labels and values as lists of data points    
        self.__state_position_2_names = Sim_Utils.generateDictionaryIndex2State(Sim_Utils.checkUniqueStateNames(variable_names)) #dictionary of keys (state indices in state vector) to values (state names) 
        self.__variable_names_2_position = Sim_Utils.convertDictionaryIndex2State(self.__state_position_2_names) #dictionary of keys (state names) to values (state indices in state vector) 
        self.max_stored_steps = num_stored_steps
        self.num_steps_stored = 1 #initialized at 1 to account for initial conditions being stored in the constructor, updated in store_data method

        #check to make sure number of states with names agrees with number of initial states
        if initial_values.size == len(self.__state_position_2_names):
            self.initialize_data_storage(next_time, self.__state_position_2_names.keys(), initial_values)
        else:
            error_message = f"Number of initial variable conditions: {initial_values.size}\
                        is different than the number of states with names: {len(self.__state_position_2_names)}"
            print(error_message)
            sys_exit(1)
    
    def __str__(self) -> str:
        #FIXME
        msgStr = Base_Component.__str__(self)
        msgStr = msgStr + "\nThis component is responsible for storing data generated by other components."
        return msgStr
    
    def initialize_data_storage(self, next_time: float, variable_names: str | list[str], variable_initial_conditions: np.array) -> None:
        """
        _Populates the keys for the data storage dictionary. Should be called at the end of the constructor after all necessary attributes have been defined._

        Parameters
        ----------
        variable_names : str or list of str
            The name(s) of the variable(s) for which to initialize data storage.
        """
        if isinstance(variable_names, str):
            variable_names = [variable_names]
        
        counter = 0
        self.__data_storage[0] = arr.array('d',[next_time])  # Initialize time storage with the initial time
        for name in variable_names:
            self.__data_storage[name] = arr.array('d',[variable_initial_conditions[counter]])  # Initialize with an empty array of doubles
            counter+=1
            
    def store_data(self, current_time: float, data: np.array) -> None:
        """
        Stores data generated by this component.

        Parameters
        ----------
        current_time : float
            The current simulation time at which the data is being stored [s].
        data : np.array 
            numpy array of state data stored where each index + 1 corresponds to the state index in the state vector. 
            this corresponds to the keys of the state_position_2_names dictionary which maps state indices to state names.
        """
        
        if data.size != len(self.__state_position_2_names):
            raise ValueError(f"Data size {data.size} does not match the number of states with names {len(self.__state_position_2_names)}")
        self.__data_storage[0].append(current_time) # Store the current time in the time storage list
        for i in np.arange(1, data.size + 1): #the first index is for time!
            self.__data_storage[i].append(data[i])
        
        self.num_steps_stored += 1
            
    
    def get_all_stored_data(self) -> dict:
        """
        Returns data storage dictionary

        Returns
        -------
        dict
            _Key is 0 through number of time + states and each value is a python array of floats of corresponding state data (or time)_
        """
        return self.__data_storage
    
    def get_stored_data(self, data_label: str | list[str] | None = None, data_time: float | None = None):
        pass
        # TODO: implement data_time filtering and error handling for invalid labels and label types
        # """
        # Returns the stored data for a given label (or list of labels), or all stored data if no label is provided.

        # Parameters
        # ----------
        # data_label : str, list of str, or None
        #     A single data label (str), a list of data labels, or None to return all data.
        # data_time : float or None
        #     If provided, filters data to only include entries up to and including the given time.

        # Returns
        # -------
        # dict or list
        #     - If data_label is None: returns the entire data storage dict.
        #     - If data_label is a single str: returns the data list for that label.
        #     - If data_label is a list of str: returns a dict mapping each label to its data list.
        # """
        # if data_time is None:
        #     raise NotImplementedError("data_time filtering is not yet implemented.")

        # if data_label is not None:
        #     # Single label (string)
        #     if isinstance(data_label, str):
        #         try:
        #             return self.__data_storage[data_label]
        #         except KeyError as e:
        #             error_message = f"Data label '{data_label}' not found in stored data."
        #             raise KeyError(error_message) from e

        #     # Multiple labels (list)
        #     elif isinstance(data_label, list):
        #         result = {}
        #         for label in data_label:
        #             if not isinstance(label, str):
        #                 error_message = f"All data labels must be strings. Got {type(label).__name__}: '{label}'."
        #                 raise TypeError(error_message)
        #             try:
        #                 result[label] = self.__data_storage[label]
        #             except KeyError as e:
        #                 error_message = f"Data label '{label}' not found in stored data."
        #                 raise KeyError(error_message) from e
        #         return result

        #     else:
        #         error_message = f"data_label must be a string or a list of strings. Got {type(data_label).__name__}."
        #         raise TypeError(error_message)

        # # No label(s) provided — return everything
        # return self.__data_storage
    
    def get_state_position_2_names(self, indices = None):
        if indices is None:
            return np.array(list(self.__state_position_2_names.values()))
        elif isinstance(indices, int):
            if indices not in self.__state_position_2_names:
                raise KeyError(f"indices {indices} not found in dictionary")
            return list(self.__state_position_2_names[indices])
        elif isinstance(indices, np.ndarray): 
            stateNames = []
            for key in indices:
                if key not in self.__state_position_2_names:
                    raise KeyError(f"Key {key} not found in dictionary")
                stateNames.append(self.__state_position_2_names[key])
            return stateNames
        else:
            print("Error: Improper Key Type Not In Dictionary") #add indices type, also add to logger
            sys_exit(1)

    def get_variable_names_2_position(self, indices = None) -> list:
        if indices is None:
            return list(self.__variable_names_2_position.values())
        elif isinstance(indices, str): 
            statePos = []
            for key in indices:
                if key not in self.__variable_names_2_position:
                    raise KeyError(f"Key {key} not found in dictionary")
                statePos.append(self.__variable_names_2_position[key])
            return statePos
        else:
            print("Error: Improper Key Type Not In Dictionary") #add indices type, also add to logger
            sys_exit(1)