#atmosphere_models

#Import Statements:
import numpy as np

class Atmosphere_Models:
    @staticmethod
    def simple1976EarthAtmosphere(altitude_m):
        """
        Returns the speed of sound (m/s) and density (kg/m^3) as a function of altitude (meters).
        Based on the 1976 U.S. Standard Atmosphere.

        Generated by ChatGPT using mathematical models from the 1976 U.S. Standard Atmosphere 
        and related physics principles. Models adapted and implemented for Python on November 25, 2024.

        Parameters:
            altitude_m (float): Altitude in meters (valid range: 0 to 25,000 m).

        Returns:
            tuple: (speed_of_sound, density) where:
                - speed_of_sound: Speed of sound in m/s.
                - density: Air density in kg/m^3.
        """
        # Constants
        P0 = 101325  # Sea-level standard pressure, Pa
        T0 = 288.15  # Sea-level standard temperature, K
        g0 = 9.80665  # Standard gravitational acceleration, m/s^2
        R = 287.05  # Specific gas constant for air, J/(kg·K)
        gamma = 1.4  # Ratio of specific heats for air
        lapse_rate = -0.0065  # Temperature lapse rate, K/m (troposphere)
        
        # Check altitude and calculate properties
        if altitude_m <= 11000:  # Troposphere
            T = T0 + lapse_rate * altitude_m  # Temperature
            P = P0 * (T / T0) ** (-g0 / (R * lapse_rate))  # Pressure
        elif altitude_m <= 20000:  # Tropopause (isothermal layer)
            T = 216.65  # Constant temperature
            P = 22632.06 * np.exp(-g0 * (altitude_m - 11000) / (R * T))  # Pressure
        else:
            # Extended layers not needed for now; calculations can be added for higher altitudes
            T = 216.65
            P = 5474.89 * (T / 216.65) ** (-g0 / (R * lapse_rate))

        # Density from Ideal Gas Law
        density = P / (R * T)

        # Speed of sound
        speed_of_sound = np.sqrt(gamma * R * T)
        
        return speed_of_sound, density
        #--------------------------------------------------------------PREVIOUS CODE
        ## Constants
        # P0 = 101325  # Sea-level standard pressure, Pa
        # T0 = 288.15  # Sea-level standard temperature, K
        # g0 = 9.80665  # Standard gravitational acceleration, m/s^2
        # R = 287.05  # Specific gas constant for air, J/(kg·K)
        # gamma = 1.4  # Ratio of specific heats for air
        
        # # Troposphere constants
        # lapse_rate = -0.0065  # Temperature lapse rate, K/m (for the troposphere)
        
        # # If the altitude is within the troposphere (0 to 11 km)
        # if altitude_m <= 11000:
        #     # Apply the Barometric formula
        #     T = T0 + lapse_rate * altitude_m  # Temperature at altitude
        #     P = P0 * (T / T0) ** (-g0 / (R * lapse_rate))  # Pressure at altitude
            
        #     # Apply the Ideal Gas Law to find the density
        #     density = P / (R * T)
            
        #     # Calculate the speed of sound
        #     speed_of_sound = np.sqrt(gamma * R * T)
        # else:
        #     # For altitudes above the troposphere (above 11 km), we assume an isothermal layer for simplicity
        #     T = 216.65  # Temperature is constant at 216.65 K
        #     P = P0 * np.exp(-g0 * (altitude_m - 11000) / (R * T))  # Pressure using exponential decay
            
        #     # Apply the Ideal Gas Law to find the density
        #     density = P / (R * T)
            
        #     # Calculate the speed of sound
        #     speed_of_sound = np.sqrt(gamma * R * T)

        # return speed_of_sound, density
        #--------------------------------------------------------------PREVIOUS CODE
        ## Constants
        # P0 = 101325  # Sea-level standard pressure, Pa
        # g0 = 9.80665  # Standard gravitational acceleration, m/s^2
        # R = 287.05  # Specific gas constant for air, J/(kg·K)
        # gamma = 1.4  # Ratio of specific heats for air
        
        # # Layer data: [base_altitude (m), base_temp (K), temp_lapse_rate (K/m)]
        # layers = [
        #     (0, 288.15, -0.0065),    # Troposphere (0–11 km)
        #     (11000, 216.65, 0.0),    # Tropopause (11–20 km)
        #     (20000, 216.65, 0.001),  # Stratosphere (20–32 km)
        #     (32000, 228.65, 0.0028), # Stratosphere (32–47 km)
        #     (47000, 270.65, 0.0),    # Stratopause (47–51 km)
        #     (51000, 270.65, -0.0028),# Mesosphere (51–71 km)
        #     (71000, 214.65, -0.002)  # Mesosphere (71–86 km)
        # ]
        
        # # Find the current atmospheric layer
        # for i, layer in enumerate(layers):
        #     if altitude_m < layer[0]:
        #         break
        # else:
        #     i = len(layers) - 1
        
        # base_alt, base_temp, lapse_rate = layers[i - 1 if i > 0 else 0]
        
        # # Calculate temperature and pressure
        # if lapse_rate == 0:  # Isothermal layer (e.g., tropopause)
        #     temp = base_temp
        #     pressure = P0 * np.exp(-g0 / (R * base_temp) * (altitude_m - base_alt))
        # else:  # Gradient layer
        #     temp = base_temp + lapse_rate * (altitude_m - base_alt)
        #     pressure = P0 * (temp / base_temp) ** (-g0 / (R * lapse_rate))
        
        # # Calculate density using the corrected formula
        # density = pressure / (R * temp)
        
        # # Calculate speed of sound
        # speed_of_sound = np.sqrt(gamma * R * temp)
        
        # return speed_of_sound, density
        #--------------------------------------------------------------PREVIOUS CODE
        # # Constants
        # T0 = 288.15  # Sea-level standard temperature, K
        # P0 = 101325  # Sea-level standard pressure, Pa
        # rho0 = 1.225  # Sea-level standard density, kg/m^3
        # g0 = 9.80665  # Standard gravitational acceleration, m/s^2
        # R = 287.05  # Specific gas constant for air, J/(kg·K)
        # gamma = 1.4  # Ratio of specific heats for air
        
        # # Layer data: [base_altitude (m), base_temp (K), temp_lapse_rate (K/m)]
        # layers = [
        #     (0, 288.15, -0.0065),    # Troposphere (0–11 km)
        #     (11000, 216.65, 0.0),    # Tropopause (11–20 km)
        #     (20000, 216.65, 0.001),  # Stratosphere (20–32 km)
        #     (32000, 228.65, 0.0028), # Stratosphere (32–47 km)
        #     (47000, 270.65, 0.0),    # Stratopause (47–51 km)
        #     (51000, 270.65, -0.0028),# Mesosphere (51–71 km)
        #     (71000, 214.65, -0.002)  # Mesosphere (71–86 km)
        # ]
        
        # # Find the current atmospheric layer
        # for i, layer in enumerate(layers):
        #     if altitude_m < layer[0]:
        #         break
        # else:
        #     i = len(layers) - 1
        
        # base_alt, base_temp, lapse_rate = layers[i - 1 if i > 0 else 0]
        
        # # Calculate temperature and pressure
        # if lapse_rate == 0:  # Isothermal layer
        #     temp = base_temp
        #     pressure = P0 * np.exp(-g0 / (R * base_temp) * (altitude_m - base_alt))
        # else:  # Gradient layer
        #     temp = base_temp + lapse_rate * (altitude_m - base_alt)
        #     pressure = P0 * (temp / base_temp) ** (-g0 / (R * lapse_rate))
        
        # # Calculate density
        # density = pressure / (R * temp)
        
        # # Calculate speed of sound
        # speed_of_sound = np.sqrt(gamma * R * temp)
        
        # return speed_of_sound, density